### ISSUE TITLE
Outdated and invalid links

### ISSUE THREAD

**Issue by takahser** [darwinia-network/awesome-darwinia#19]
A lot of the links in this repo are currently outdated or invalid:

**HTTP 404 errors:**

- https://docs.crab.network/builders/get-started/darwinia-dev/
- https://docs.darwinia.network/tutorials/quick-start-account
- https://docs.darwinia.network/understand-darwinia/wiki-us-architecture
- https://docs.darwinia.network/bridge-knowledge-base/bridge-overview
- https://docs.darwinia.network/developers/dev-home

**Expired:**

- https://t.me/+fJiD_IwvwjhjYmQ9

**No response:**

- https://wormhole.darwinia.network/
- https://metarock.app/
- https://subswap.pro/#/swap

**Comment by acgxv** [comment]
Thank you for submitting the report. 

Could you please follow up on these, @wuminzhe?

**Comment by wuminzhe** [comment]
ok

**Comment by wuminzhe** [comment]
fixed: https://github.com/darwinia-network/awesome-darwinia/commit/3bad98ee829c98f17ed09160d7cb60f7cfe98e84
