### ISSUE TITLE
Maintain and update outdated contents

### ISSUE THREAD

**Issue by acgxv** [darwinia-network/awesome-darwinia#22]

**Comment by hackfisher** [comment]
dcdao is maintaining it.

**Comment by acgxv** [comment]
Lots of content is outdated; I believe this should remain open until it gets updated.

**Comment by acgxv** [comment]
BTW, I came from Google search. This repository holds some significance.

**Comment by nblogist** [comment]
Thanks!! Will start looking at it later this week!!
